version: "3.8"

services:
  api:
    build: .
    container_name: nestjs_api
    restart: always
    env_file: .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: listik
      DB_PASSWORD: root
      DB_NAME: multivision
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      environment:
      POSTGRES_USER: listik
      POSTGRES_PASSWORD: root
      POSTGRES_DB: multivision
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U listik -d multivision"]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - app-network


volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge